basicApp/urls.py
from basicApp import views
from django.urls import path


''' This app_name is used in html pages in href. Html page checks this app_name for the url.'''

app_name = 'basicApp'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),

]

learningTemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicApp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage, name='home'),
    path('basicApp/', include('basicApp.urls')),
]

basicApp/models.py
from django.db import models

# Create your models here.

basicApp/views.py
from django.shortcuts import render

# Create your views here.

def homePage(request):
    return render(request, 'basicApp/home.html')


def index(request):
    d = {'text': 'hello world', 'numbers': 25}
    return render(request, 'basicApp/index.html', context=d)


def other(request):
    return render(request, 'basicApp/other.html')


def relative(request):
    return render(request, 'basicApp/relUrlTemp.html')

templates/basicApp/base.html
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">HomePage</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'basicApp:index' %}">Index <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'basicApp:other' %}">OtherPage</a>
          <a class="dropdown-item" href="{% url 'basicApp:relative' %}">RelativePage</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <div class="container">
    {% block body_block %}
        
<!--Anything outside to it, will be inherited if you extend.-->
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/basicApp/home.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
{% block body_block %}
    <h1>HOME PAGE</h1>
    <h3> Check my custom filter here by clicking on <strong> <a href="{% url 'basicApp:index' %}">INDEX</a></strong> on Navbar.</h3>
{% endblock %}

templates/basicApp/index.html
<!DOCTYPE html>
{% extends "basicApp/base.html" %}
{% load basicApp_extras %} <!--loading custom filters file (in basicApp/templatetags/ path) -->
{% block body_block %}
    <h1>INDEX PAGE </h1>
    <h2> '{{text}}' is the first key. Cut the 'hello' part.</h2>
    <h2> {{text|cut:'hello'}} </h2>
    <hr>
    <h2> {{numbers}} is the key</h2>
    <h2>  Adding 20 to {{numbers}}: {{numbers|add:20}} </h2>
    <hr>
    <h1> Added my custom  square filter. </h1>
    <p> (To create your own filter, add a directory 'templatetags' add '__init__.py' and a python file)</p>
<h3> <a href="https://docs.djangoproject.com/en/2.2/howto/custom-template-tags/"> Check how to create custom filters here.</a></h3>
    <h2> The square of {{numbers}} is {{numbers|sq}} </h2>
    <hr>
{% endblock %}

templates/basicApp/other.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
{% block body_block%}
    <h1>OTHER PAGE</h1>
{% endblock %}

templates/basicApp/relUrlTemp.html
<!DOCTYPE html>

{% extends "basicApp/base.html" %}
{% block body_block%}
    <h1>RELATIVE URL TEMPLATE</h1>
{% endblock %}